AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: awseb-AWSEB-10U5CTRCKIG8B-1047931632.us-east-1.elb.amazonaws.com
          Id: awseb-AWSEB-10U5CTRCKIG8B
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        Comment: booktracker-app
        DefaultCacheBehavior:
          TargetOriginId: awseb-AWSEB-RHP6P2EAL60O
          SmoothStreaming: 'false'
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: all
          ViewerProtocolPolicy: "redirect-to-https"
        PriceClass: PriceClass_200
        Restrictions:
          GeoRestriction:
            RestrictionType: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
