
ansible --version
sudo nano haya-key.pem
cd /etc/ansible
vim hosts

[ubuntu]
node1 ansible_host=3.80.198.69 ansible_user=ubuntu


[all:vars]
ansible_ssh_private_key_file=/home/ec2-user/haya-key.pem


sudo chmod 400 haya-key.pem

sudo ansible ubuntu -m ping

sudo mkdir playbooks
cd playbooks

sudo nano aws.yml
sudo nano mvn-java.yml
sudo nano jenkins.yml
sudo nano docker.yml

sudo ansible-playbook aws.yml
sudo ansible-playbook mvn-java.yml
sudo ansible-playbook jenkins.yml
sudo ansible-playbook docker.yml





